# Generated by Django 3.1.2 on 2020-10-12 04:12

from os import name
from django.db import migrations, models
import django.db.models.deletion
from api.user.models import CustomUser


class Migration(migrations.Migration):

    def seed_data(apps, schema_editor):
        user = CustomUser(name="sumeet", email="sumeet@gmail.com",
                          is_staff=True, is_superuser=True, phone="8888987679")
        user.set_password("1234")
        user.save()

    dependencies = [
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
